export { AboutPage } from './About'
export { ContactPage } from './Contact'
export { HomePage } from './Home'
export { PrintsPage } from './Prints'
export { ProjectsPage } from './Projects'
export * from './Projetos'
